paths:
  /shoppr/api/v1/addItem:
    get:
      operationId: addItem
      parameters:
      - in: query
        name: Item
        type: string
      - format: int64
        in: query
        name: Amount
        type: integer
      responses:
        "200":
          description: ""
      summary: Add item to basket.
      tags:
      - basket
  /shoppr/api/v1/basket:
    get:
      operationId: basket
      responses:
        "200":
          $ref: '#/responses/map[string]int'
      summary: Show contents of basket.
      tags:
      - basket
  /shoppr/api/v1/checkout:
    get:
      operationId: checkout
      responses:
        "200":
          $ref: '#/responses/map[string]float64'
      summary: Calculate checkout details.
      tags:
      - basket
  /shoppr/api/v1/createCoupon:
    get:
      operationId: createCoupon
      parameters:
      - format: int64
        in: query
        name: Duration
        type: integer
      - format: double
        in: query
        name: Discount
        type: number
      - in: query
        name: Target
        type: string
      responses:
        "200":
          $ref: '#/responses/Coupon'
      summary: Create a new coupon for given duration, discount and target item.
      tags:
      - coupon
  /shoppr/api/v1/deleteCoupon:
    get:
      operationId: deleteCoupon
      parameters:
      - in: query
        name: Coupon
        type: string
      responses:
        "200":
          description: ""
      summary: Delete a coupon.
      tags:
      - coupon
  /shoppr/api/v1/listCoupons:
    get:
      operationId: listCoupons
      responses:
        "200":
          $ref: '#/responses/Coupon'
      summary: List all coupons.
      tags:
      - coupon
  /shoppr/api/v1/listItems:
    get:
      operationId: listItems
      responses:
        "200":
          $ref: '#/responses/Coupon'
      summary: List all coupons.
      tags:
      - shop
  /shoppr/api/v1/purchase:
    get:
      operationId: purchase
      parameters:
      - in: query
        name: Coupon
        type: string
        x-go-name: CCexpiry
      responses:
        "200":
          $ref: '#/responses/map[string]float64'
      summary: Purchase basket.
      tags:
      - basket
  /shoppr/api/v1/reset:
    get:
      operationId: reset
      responses:
        "200":
          description: ""
      summary: Reset all data for testing.
      tags:
      - reset
  /shoppr/api/v1/updateCoupon:
    get:
      operationId: updateCoupon
      parameters:
      - format: int64
        in: query
        name: Duration
        type: integer
      - format: double
        in: query
        name: Discount
        type: number
      - in: query
        name: Target
        type: string
      responses:
        "200":
          $ref: '#/responses/Coupon'
      summary: Update an existing coupon with given duration, discount and target
        item.
      tags:
      - coupon
swagger: "2.0"
